window.playlist = [
	{composer : "さふらむ", title : "5 team creators", file_name : "5 team creators.mp3"},
	{composer : "さふらむ", title : "Be in imminent denger!", file_name : "Be in imminent denger!.mp3"},
	{composer : "さふらむ", title : "B-rush!!", file_name : "B-rush!!.mp3"},
	{composer : "さふらむ", title : "Congratulations", file_name : "Congratulations.mp3"},
	{composer : "さふらむ", title : "ED yuanxian", file_name : "ED yuanxian.mp3"},
	{composer : "さふらむ", title : "Hearts of Adventurers", file_name : "Hearts of Adventurers.mp3"},
	{composer : "さふらむ", title : "illuminations", file_name : "illuminations.mp3"},
	{composer : "さふらむ", title : "Past×Present", file_name : "Past×Present.mp3"},
	{composer : "さふらむ", title : "start", file_name : "start.mp3"},
	{composer : "さふらむ", title : "You are failed……", file_name : "You are failed…….mp3"},
	{composer : "さふらむ", title : "そうげん", file_name : "そうげん.mp3"},
	{composer : "さふらむ", title : "ハカイ(BMS EXedit)", file_name : "ハカイ(BMS EXedit).mp3"},
	{composer : "さふらむ", title : "暗光", file_name : "暗光.mp3"},
	{composer : "さふらむ", title : "見上げて……", file_name : "見上げて…….mp3"},
	{composer : "さふらむ", title : "荒涼の町", file_name : "荒涼の町.mp3"},
	{composer : "さふらむ", title : "桜日和(short)", file_name : "桜日和(short).mp3"},
	{composer : "さふらむ", title : "寝坊：約1分登校～バンコクさんのテーマ～EQ", file_name : "寝坊：約1分登校～バンコクさんのテーマ～EQ.mp3"},
	{composer : "さふらむ", title : "達磨散りゆくままに", file_name : "達磨散りゆくままに.mp3"},
	{composer : "NSWK", title : "are", file_name : "are.mp3"},
	{composer : "NSWK", title : "METAL P Computing unit", file_name : "METAL P Computing unit.mp3"},
	{composer : "NSWK", title : "stand by me(NSWK)", file_name : "stand by me(NSWK).mp3"},
	{composer : "NSWK", title : "TEKITO", file_name : "TEKITO.mp3"},
	{composer : "NSWK", title : "YO-KAI DISCO", file_name : "YO-KAI DISCO.mp3"}
];